version: '3'

services:
  bridge0:
    container_name: bridge0
    image: "celestia-node:testnet"
    environment:
      - NODE_TYPE=bridge
    command: [
            "celestia", "bridge",
            "--node.store", "/celestia-bridge",
            "start",
            "--core.remote", 
            "tcp://192.167.10.0:26657",
            "--headers.trusted-hash", 
            "02EED4BCFAF0CC8A3D1100D588E571FBF44219488F01AB48870BC9015A9F105A"
             ]
    volumes:
       - ${PWD}/celestia-node/bridge/bridge0/nodekey0:/celestia-bridge/keys/OAZHALLLMV4Q:ro
    networks:
      localnet:
        ipv4_address: 192.167.1.0

networks:
  localnet:
    name: localnet
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
