version: '3'

services:
  dalc0:
    container_name: dalc0
    image: "celestia-node:v0.4.1"
    environment:
      - NODE_TYPE=bridge
    command: [
            "celestia", "bridge",
            "start",
            "--node.network", "private",
            "--core.ip", "192.167.10.0",
            "--keyring.accname", "key-1",
            "--node.store", "/root/.celestia-bridge-arabica"
             ]
    volumes:
       - ${PWD}/celestia-app/private/keyring-test:/root/.celestia-bridge-arabica/keys/keyring-test:ro
       - ${PWD}/celestia-node/bridge/config.toml:/root/.celestia-bridge-arabica/config.toml
    ports:
      - "26658:26658"

    networks:
      localnet:
        ipv4_address: 192.167.3.0

networks:
  localnet:
    name: localnet
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.0.0/16
