version: '3'

services:
  dalc0:
    container_name: dalc0
    image: "ghcr.io/celestiaorg/dalc:sha-b46432b"
    environment:
      - NODE_TYPE=light
      - MY_VAL_ADDRESS=celes1dm7fp7uwrr5y68v48gg8jhd2cku7vt7f4l8w0s
      - CELESTIA_PRIVATE_GENESIS=942D98EA04EE31F523D5B5BF5B5E801CEB5BC4AD060BBF5B656E6C30A0EDCE1B
    command: [
            "celestia", "light",
            "--node.store", "/dalc",
            "start",
            "--headers.trusted-peers",
            "/ip4/192.167.1.0/tcp/2121/p2p/12D3KooWL8z3KARAYJcmExhDsGwKbjChKeGaJpFPENyADdxmEHzw",
            "--headers.trusted-hash",
            "942D98EA04EE31F523D5B5BF5B5E801CEB5BC4AD060BBF5B656E6C30A0EDCE1B"
             ]
    volumes:
       - ${PWD}/dalc/celestia-app/keyring-test/:/root/keyring-test/:ro
       - ${PWD}/dalc/optimint_server.toml:/dalc/optimint_server.toml
       - ${PWD}/dalc/celestia-light/data/LOCK:/dalc/data/LOCK
       - ${PWD}/dalc/celestia-light/config.toml:/dalc/config.toml
       - ${PWD}/dalc/celestia-light/keys/OAZHALLLMV4Q:/dalc/keys/OAZHALLLMV4Q

    networks:
      localnet:
        ipv4_address: 192.167.3.0

networks:
  localnet:
    name: localnet
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
