version: '3'

services:
  ethermint0:
    container_name: ethermint0
    image: "ghcr.io/celestiaorg/ethermint-debug:${ETHERMINT_IMAGE_TAG-latest}"
    command: [
            "dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec",
            "/usr/bin/ethermintd", "--", "start",
            "--optimint.aggregator", "true",
            "--optimint.block_time", "30s",
            "--optimint.namespace_id", "0000DEADBEEF0000",
            "--optimint.da_layer", "grpc",
            "--optimint.da_config", '{"host":"192.167.3.0", "port":4200}',
            "--rpc.laddr", "tcp://0.0.0.0:26657",
            "--json-rpc.enable", "true",
            "--json-rpc.api", "eth,txpool,personal,net,web3,miner",
            "--json-rpc.address", "0.0.0.0:8545",
             ]
    volumes:
         - ${PWD}/ethermint/ethermint0/config/priv_validator_key.json:/root/.ethermint/config/priv_validator_key.json:ro
         - ${PWD}/ethermint/ethermint0/config/node_key.json:/root/.ethermint/config/node_key.json:ro
         - ${PWD}/ethermint/ethermint0/config/config.toml:/root/.ethermint/config/config.toml:ro
         - ${PWD}/ethermint/ethermint0/keyring-test:/root/.ethermint/keyring-test:ro
         - ${PWD}/ethermint/genesis.json:/root/.ethermint/config/genesis.json:ro
    ports:
      # Expose the EVM json-rpc server
      - 8545:8545
      # Debug port
      - 40000:40000
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    networks:
      localnet:
        ipv4_address: 192.167.4.0

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
