version: '3'

services:
  ethermint0:
    container_name: ethermint0
    image: "ghcr.io/astriaorg/ethermint:${ETHERMINT_IMAGE_TAG:-eth-hashes-991f829}"
    environment:
      - HOME_DIR=/root/.ethermintd
    command: [
            "ethermintd", "start",
            "--keyring-backend", "test"
             ]
    volumes:
         - ${PWD}/.ethermintd/config/priv_validator_key.json:/root/.ethermintd/config/priv_validator_key.json:ro
         - ${PWD}/.ethermintd/data/priv_validator_state.json:/root/.ethermintd/data/priv_validator_state.json:ro
         - ${PWD}/.ethermintd/config/node_key.json:/root/.ethermintd/config/node_key.json:ro
         - ${PWD}/.ethermintd/config/config.toml:/root/.ethermintd/config/config.toml
         - ${PWD}/.ethermintd/config/genesis.json:/root/.ethermintd/config/genesis.json:ro
         - ${PWD}/.ethermintd/keyring-test:/root/.ethermintd/keyring-test:ro
    ports:
      # Expose the EVM json-rpc server
      - 8545:8545
      # Expose websocket
      - 8546:8546
    networks:
      localnet:
        ipv4_address: 192.167.4.0

networks:
  localnet:
    name: localnet
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.0.0/16
