version: '3'

services:
  dalc0:
    container_name: dalc0
    image: "ghcr.io/celestiaorg/optimint-mockserv:e430cb4"
    networks:
      localnet:
        ipv4_address: 192.167.3.0

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
